[metadata]
name = "name-printer"
description = "Prints your name to a file in seconds!" # XD

[[questions.name]]
ques = "What is your name?"
type = "input"

[filestructure]
"name.txt" = "true"

[content]
"name.txt" = '''
{{index . "name"}}
'''

[commands-after]
1 = ["git init", "true"]
2 = ["git add .", "true"]
3 = ["git commit -m 'Initial commit by cakecutter'", "true"]