[metadata]
name = "name-printer"
description = "Prints your name to a file in seconds!" # XD

[[questions.name]]
ques = "What is your name?"
type = "input"

[batter]
1 = ["git init", "true"]

[filestructure] 
"name.txt" = "true"

[content]
"name.txt" = '''
{{index .Ans "name"}} is in {{.Os}}
'''